server:
  port: 8082
  servlet:
    context-path: /sell

logging:
  config: classpath:logback-spring.xml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.180.135:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  jackson:
#   如果返回结果中存在null但不需要给前端返回时，那么可以增加该配置；如果String返回结果为null，前端需要String为""时，可在VO中设置默认值
    default-property-inclusion: non_null