server:
  port: 8082
  servlet:
    context-path: /sell

logging:
  config: classpath:logback-spring.xml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.180.134:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none